### ISSUE TITLE
GitHub Link not working

### ISSUE THREAD

**Issue by rphlhxfld** [TheBlackbird14/ConsoleGamesLib#6]
GitHub link doesn't work.

1. Type in the console of an Alpine Linux capable device :
```

wget https://github.com/TheBlackbird14/ConsoleGamesLibreleases/download/{version}/ConsoleGamesLib.{version}.zip

```

Expected behavior:
	The Link should download the zip file of the last release.

![image](https://github.com/TheBlackbird14/ConsoleGamesLib/assets/124580442/8a725a97-b639-4b58-bf81-801d1893be49)

**Comment by TheBlackbird14** [comment]
Hi @RaphaelGHG,
my mistake, the link might be a little misleading. It is just meant as a placeholder, as you can see by the "{version}" in parts of the link. This is because there are multiple versions of the library. The newest link is https://github.com/TheBlackbird14/ConsoleGamesLib/releases/download/v2.1.1/ConsoleGamesLibv2.1.1.zip. Hope this works for you know. btw you're missing a / in your link as well, between ConsoleGamesLib and releases.
